fix(mutation-testing-metrics): fix groupBy function
the groupBy function uses an object as accumulator, which inherits special
properties like `__proto__`. This causes the nullish coalescing assignment
operator to skip creating an array for these grouping keys, causing the error
`TypeError: acc[key].push is not a function`.

closes: #4059